--Q.1 What  is total revenue generated by male vs female customer?
select gender, sum(purchase_amount) as revenue
from customer 
group by gender;

--Q.2 Which customer use discount but still spent more then the average purchasse amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >= ( SELECT AVG(purchase_amount)FROM customer);

--Q.3 Which are top 5 products with highest average review rating?
SELECT item_purchased,
ROUND(AVG(review_rating)::numeric, 2) AS "purchase_product_rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--Q.4 Compare the average purchase amount between standard and express shipping ?
SELECT shipping_type,
ROUND(AVG(purchase_amount), 4) AS average_purchase
FROM customer
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;

--Q.5 Do subcribed customer spend more?compare average spend and total revenue 
--between subcriber and non subcriber?
select subscription_status, count(customer_id) as total_customer,
round(avg(purchase_amount), 2) avg_spend,
round(sum(purchase_amount), 2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Q.6 Which five product have the highest percentage with discount applied?

SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 
ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC LIMIT 5;

--Q.7 Segment customer into new returning, and loyel based on their total.
--number of previous purchases, and show the count of each segment ?
WITH customer_type AS (
SELECT customer_id,previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
    FROM customer
)
SELECT customer_segment,COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

--Q.8 Whatare the to three most purchase product with in each category?
with item_count as(
select category,item_purchased,
count(customer_id)as total_orders,
ROW_NUMBER() OVER(partition by category order by count(customer_id)desc) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_count where item_rank <=3;
--Q.9 Are customer who are repeat buyer (most than 5 precious purchase )also
--likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from customer where previous_purchases >5
group by subscription_status
--Q.10 What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;